version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck       # Check for unchecked errors
    - govet          # Report suspicious constructs
    - ineffassign    # Detect ineffective assignments
    - staticcheck    # Static analysis checks (includes gosimple)
    - unused         # Find unused code
    - misspell       # Find misspellings
    - unconvert      # Remove unnecessary conversions
    - unparam        # Find unused function parameters
    - nakedret       # Find naked returns in long functions
    - prealloc       # Find slice preallocation opportunities
    - copyloopvar    # Check for pointers to loop variables
    - bodyclose      # Check HTTP response body is closed
    - noctx          # Check for HTTP requests without context

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false

    nakedret:
      max-func-lines: 30

    prealloc:
      simple: true
      range-loops: true
      for-loops: true

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - unparam
          - prealloc

      - path: tests/
        linters:
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/rapidodb/rapidodb

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
